services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres-aws
    env_file:
      - ./.en
    ports:
      - '3000:3000'
    depends_on:
      - redis
    volumes:
      - ./src:/app/src